In [1]:
import cv2 as cv

In [2]:
img = cv.imread("Teletubbies.jpg")
type(img)

numpy.ndarray

In [3]:
# RGB BGR 
img

array([[[ 62,  47,  21],
        [ 42,  27,   1],
        [ 44,  27,   1],
        ...,
        [ 59,  41,   4],
        [ 61,  43,   6],
        [ 61,  43,   6]],

       [[155, 141, 113],
        [138, 122,  93],
        [137, 120,  93],
        ...,
        [127, 109,  68],
        [126, 106,  65],
        [124, 106,  65]],

       [[172, 157, 124],
        [155, 141, 105],
        [153, 136, 103],
        ...,
        [134, 111,  65],
        [142, 118,  72],
        [141, 118,  72]],

       ...,

       [[ 55, 175, 151],
        [ 11, 131, 107],
        [ 12, 132, 108],
        ...,
        [  6, 110,  99],
        [ 10, 115, 102],
        [ 19, 124, 109]],

       [[ 56, 176, 152],
        [ 12, 132, 108],
        [ 12, 132, 108],
        ...,
        [ 13, 117, 106],
        [ 22, 127, 114],
        [ 34, 139, 124]],

       [[ 56, 176, 152],
        [ 12, 132, 108],
        [ 13, 133, 109],
        ...,
        [ 23, 127, 116],
        [ 22, 127, 114],
        [ 36, 141, 126]]

In [4]:
img.shape

(208, 242, 3)

In [5]:
cv.imshow('New Image',img,)
while True:
    k = cv.waitKey(1) & 0xFF
    if k == 27:
        break
cv.destroyAllWindows()

In [6]:
gray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
cv.imshow("Gray",gray)
while True:
    k = cv.waitKey(1) & 0xFF
    if k == 27:
        break
cv.destroyAllWindows()

In [7]:
gray.shape

(208, 242)

In [8]:
gray

array([[ 41,  21,  21, ...,  32,  34,  34],
       [134, 115, 114, ...,  99,  96,  96],
       [149, 132, 128, ..., 100, 107, 107],
       ...,
       [154, 110, 111, ...,  95,  99, 108],
       [155, 111, 111, ..., 102, 111, 123],
       [155, 111, 112, ..., 112, 111, 125]], dtype=uint8)

In [9]:
blur = cv.GaussianBlur(img,(11,11),cv.BORDER_DEFAULT)
cv.imshow("Blur",blur)
while True:
    k = cv.waitKey(1) & 0xFF
    if k == 27:
        break
cv.destroyAllWindows()

In [10]:
cv.imshow("Blur",blur)
cv.waitKey(0)
cv.destroyAllWindows()

In [11]:
im = img.copy()

In [12]:
im[:150,:150] = cv.GaussianBlur(im[:150,:150],(11,11),cv.BORDER_DEFAULT)
cv.imshow("Partially Blurred",im)
cv.waitKey(0)
cv.destroyAllWindows()

In [13]:
canny1 = cv.Canny(blur,100,100)
cv.imshow("Canny",canny1)
cv.waitKey(0)
cv.destroyAllWindows()

In [14]:
canny2 = cv.Canny(blur,20,20)
cv.imshow("Canny",canny2)
cv.waitKey(0)
cv.destroyAllWindows()

In [15]:
dilated = cv.dilate(canny1,(3,3),iterations=3)
cv.imshow("Dilated",dilated)
cv.waitKey(0)
cv.destroyAllWindows()

In [16]:
# 3x3 kernel will consider the 3x3 neighborhood around each pixel, and for each pixel, the maximum value within this neighborhood will be selected.
dilated = cv.dilate(canny1,(50,50),iterations=3)
cv.imshow("Dilated",dilated)
cv.waitKey(0)
cv.destroyAllWindows()

In [17]:
# Erosion works by shrinking or thinning the boundaries of objects in an image. It involves sliding a structuring element (kernel)
#over the image, and for each pixel under the kernel, replacing its intensity value with the minimum value
eroded = cv.erode(dilated,(3,3),iterations=3)
cv.imshow("Eroding",eroded)
cv.waitKey(0)
cv.destroyAllWindows()

In [18]:
b,g,r = cv.split(img)

In [19]:
b

array([[ 62,  42,  44, ...,  59,  61,  61],
       [155, 138, 137, ..., 127, 126, 124],
       [172, 155, 153, ..., 134, 142, 141],
       ...,
       [ 55,  11,  12, ...,   6,  10,  19],
       [ 56,  12,  12, ...,  13,  22,  34],
       [ 56,  12,  13, ...,  23,  22,  36]], dtype=uint8)

In [20]:
g

array([[ 47,  27,  27, ...,  41,  43,  43],
       [141, 122, 120, ..., 109, 106, 106],
       [157, 141, 136, ..., 111, 118, 118],
       ...,
       [175, 131, 132, ..., 110, 115, 124],
       [176, 132, 132, ..., 117, 127, 139],
       [176, 132, 133, ..., 127, 127, 141]], dtype=uint8)

In [21]:
r

array([[ 21,   1,   1, ...,   4,   6,   6],
       [113,  93,  93, ...,  68,  65,  65],
       [124, 105, 103, ...,  65,  72,  72],
       ...,
       [151, 107, 108, ...,  99, 102, 109],
       [152, 108, 108, ..., 106, 114, 124],
       [152, 108, 109, ..., 116, 114, 126]], dtype=uint8)

In [22]:
cv.imshow("Blue",b)
cv.waitKey(0)
cv.destroyAllWindows()

In [23]:
cv.imshow("Green",g)
cv.waitKey(0)
cv.destroyAllWindows()

In [24]:
cv.imshow("Red",r)
cv.waitKey(0)
cv.destroyAllWindows()

In [25]:
# When cv.BORDER_CONSTANT is used, the border pixels are filled with a constant value specified by the value parameter
const = cv.copyMakeBorder(img,10,20,5,10,cv.BORDER_CONSTANT,value=(120,125,160))
cv.imshow("Border",const)
cv.waitKey(0)
cv.destroyAllWindows()

In [26]:
dst = cv.addWeighted(img,0.7,blur,0.2,0)
cv.imshow("Weighted",dst)
cv.waitKey(0)
cv.destroyAllWindows()

In [27]:
resized = cv.resize(img,(512,512),interpolation=cv.INTER_CUBIC)
cv.imshow("Resized",resized)
cv.waitKey(0)
cv.destroyAllWindows()

In [31]:
#Cropping
cropped = img[100:,50:]
cv.imshow("Cropped",cropped)
cv.waitKey(0)
cv.destroyAllWindows()